### ISSUE TITLE
newbie questions "Only planar 32-bit float is supported" 

### ISSUE THREAD

**Issue by hydra3333** [ifb/vapoursynth-tonemap#2]
For newbies (like me) ... "Only planar 32-bit float is supported" ... would you please be able to either briefly outline the formats and/or provide link(s) to stuff which outlines what these things are ?   

An example or a link to example outlining how to convert a clip to these input formats which the plugin requires would be most appreciated.

For context, a goal is to convert from HDR BT.2020 to BT.709 for encoding into avc using ffmpeg(with NVEnc) or x264, (piped via VSPIPE) so that an older media player can play the videos.    

Now I'm off to check whether nvidia's nvdec on a 750Ti and 1050Ti can decode HDR BT.2020 via Donald Graft's DGDecNV http://rationalqm.us/board/viewforum.php?f=8&sid=1c7197caea0bfda80f7071e7988c14ed and give it to Vapoursynth for input to your plugin.

Here's hoping :)

**Comment by ifb** [comment]
If you're just converting from 2020 to 709 you don't need separate tone mapping.  We're at the mercy of Vapoursynth's built-in scaling (z.lib), which comes with a warning that it's not a proper color management system.
https://github.com/sekrit-twc/zimg

If you're converting HDR (PQ/HLG) to SDR, then you probably do want tone mapping and you might find this plugin useful.  Something like the following:

    import vapoursynth as vs
    core = vs.get_core()
    
    c = core.ffms2.Source(source  = "Demo_TravelXP_4K_HDR_HLG.ts")
    c = core.resize.Lanczos(clip=c, format=vs.RGBS, 
                            width=1920, height=1080,
                            matrix_in_s="2020ncl",
                            transfer_in_s="std-b67", transfer_s="linear",
                            nominal_luminance=1000)
    c = core.tonemap.Mobius(clip=c, exposure=4)
    c = core.resize.Lanczos(clip=c, format=vs.YUV420P10, matrix_s="709",
                            primaries_in_s="2020",  primaries_s="709",
                            transfer_in_s="linear", transfer_s="709")
    c.set_output()

**Comment by hydra3333** [comment]
Wonderful !  Thank you.
