### ISSUE TITLE
tonemap causing artifacts

### ISSUE THREAD

**Issue by Selur** [ifb/vapoursynth-tonemap#3]
Got artifacts using the toneMap filter, see: https://forum.doom9.org/showthread.php?t=175324 since this doesn't happen when I use toneMap directly with current ffmpeg builds I guess this is a bug introduced during the porting to Vapoursynth or  a bug that was there and got fixed in the toneMap source.
-> would be nice if you could have a look at it.

Thanks!

**Comment by Selur** [comment]
converting to RGBS before using the filter does seem to help.

**Comment by ifb** [comment]
Linear RGB floating point is required (vs.RGBS).  tonemap should error out otherwise.  I'll change that and add a more complete usage example so it's a little more obvious.
